batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 68
model_path: TrainedModels/202310151007
train_epochs: 175
train_workers: 20
vocab:
    "g\u1EA1\xCD\u01B0\u1ED3\u1EC5\u1EE8Jy\xE9Kb\xEA\u1EF3\xDD\u0103\u1EA2O\u1EBF\
    \u1ECB\u1EE5v\xF2\u1EEFfohU5\xE2\u1EEB2HlAm6\xFA/\u1ED4\u1EEDeQz\u1EE3\u1EB5\xE1\
    \ \xD3\u1ECFd\u1EF7\u1EDF\u1EBB\u1EE9N\xF9DM\u1EE14\u0111\u1EDDk7Ptx\u1EDB\u1EAD\
    \u1EC1r1\u1EE7\u1EA4I\u1EB9\xF3\u1ED53s\xE8\u01AF\u1EF9\u1EB7\u1EBDS\u1EA5n\u1ED7\
    \u1ED9u\xE0\xE3C\u1EA9\u0110L\u1EC9\u1ECDa\u1EF5W\u1EAB\u0169\u1EC7Gc\u0129T\u01A1\
    q\u1EA3F\xEDE\u1ED1\u1EAF\u1EA7\u1EF1\xECR\xD4\xF48\xF5Y\xC2i\u1EB1B\u1EB3\xFDX\u1EC3\
    p\u1EDE'\xC19V"
width: 1408
